# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_reply_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialApp.Post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialApp.Reply'),
        ),
    ]
